### ISSUE TITLE
Firefox - Amazon Credit Card Nicknames not working

### ISSUE THREAD

**Issue by PhilipTDavis** [pip8786/CCNA#21]
I've just started using Firefox after migrating from Chrome. Credit Card Nicknames for Amazon worked well for me in Chrome so I've installed the extension in Firefox as well but it isn't allowing me to enter any nicknames. When I click on the extension it acknowledges that I'm in an Amazon wallet tab...but that's it.

**Comment by pip8786** [comment]
Hmm, I just updated the Firefox extension yesterday with all the fixes I made to the Chrome side. The biggest change was the new manifest which required me moving script files around. Maybe that broke something? I haven't tested it on Firefox since I don't use that browser but I can do that soon.

**Comment by pip8786** [comment]
I just pushed a new version. The executeScript command i was using had a syntax error that worked on Chrome but not Firefox. The fix works on both. Let me know if it works for you.

**Comment by PhilipTDavis** [comment]
I've just tried again...the update seems to be there...but I still can't get it to work. What am I doing wrong?
[Credit Card Nicknames for Amazon - Firefox.webm](https://github.com/pip8786/CCNA/assets/155070803/2e60c1b0-9ac5-4493-aec7-84a70099dac8)

**Comment by pip8786** [comment]
Thanks for the video. I see that sometimes too. Could you try pinning the extension (as shown below) and toggling it a few times on the window? That seems to bring it up eventually for me, usually on the second try. I could see if there's a timing issue with the script running too early to detect cards or something. Let me know if that works. The second screenshot is it working in Firefox for me, installed from the store.

![Screenshot 2023-12-28 at 8 13 54 PM](https://github.com/pip8786/CCNA/assets/1085106/ad18b95f-9d56-42db-b3af-e8ccd4dea756)

![Screenshot 2023-12-28 at 8 14 59 PM](https://github.com/pip8786/CCNA/assets/1085106/3fee0f7b-97e9-4b5b-8dcd-842eb912c0cc)

**Comment by PhilipTDavis** [comment]
Thanks Philippe, it all seems to be working now after I tried that.
